# Generated by Django 5.2.17 on 2026-09-27 00:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Descripción o concepto de la necesidad de gasto.', max_length=255)),
                ('monto_estimado', models.DecimalField(decimal_places=2, help_text='Importe estimado único en ARS.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unidad_requirente', models.CharField(help_text='Unidad sintética requirente de prueba.', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de presentación fijadas por el servidor.')),
                ('estado', models.CharField(choices=[('presentada', 'Presentada'), ('aceptada', 'Aceptada'), ('postergada', 'Postergada'), ('rechazada', 'Rechazada')], default='presentada', help_text='Estado del trámite (inicial: presentada).', max_length=20)),
                ('version', models.PositiveIntegerField(default=0, help_text='Versión para control de concurrencia e historial (inicial: 0).')),
                ('solicitante', models.ForeignKey(help_text='Usuario solicitante asignado por el servidor.', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_gasto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de gasto',
                'verbose_name_plural': 'Solicitudes de gasto',
                'ordering': ['-fecha_creacion', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto_estimado__gt', 0)), name='solicitud_monto_estimado_positivo'), models.CheckConstraint(condition=models.Q(('version__gte', 0)), name='solicitud_version_no_negativa')],
            },
        ),
    ]
