# Generated by Django 5.2.17 on 2026-09-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exactas fijadas por el servidor al momento de la decisión.')),
                ('motivo', models.TextField(blank=True, default='', help_text='Justificación de la decisión (obligatoria en postergación y rechazo; opcional en aceptación).')),
                ('estado_anterior', models.CharField(choices=[('presentada', 'Presentada'), ('aceptada', 'Aceptada'), ('postergada', 'Postergada'), ('rechazada', 'Rechazada')], help_text='Estado en que se encontraba la solicitud inmediatamente antes de esta decisión.', max_length=20)),
                ('estado_resultante', models.CharField(choices=[('presentada', 'Presentada'), ('aceptada', 'Aceptada'), ('postergada', 'Postergada'), ('rechazada', 'Rechazada')], help_text='Nuevo estado resultante de la solicitud tras aplicar la decisión.', max_length=20)),
                ('autor', models.ForeignKey(help_text='Usuario de prueba asignado en servidor al momento de la decisión.', on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_gasto', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(help_text='Solicitud sobre la cual recae la decisión.', on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='gastos.solicitudgasto')),
            ],
            options={
                'verbose_name': 'Decisión de gasto',
                'verbose_name_plural': 'Decisiones de gasto',
                'ordering': ['fecha', 'id'],
                'indexes': [models.Index(fields=['solicitud', 'fecha'], name='gastos_deci_solicit_fdf972_idx')],
            },
        ),
    ]
